export default {
  LOGIN: "Login",
  REGISTER: "Register",
  HOME: "Home",
  PRODUCTS: "Products",
  PRODUCT_DETAIL: "Detail",
  CARRITO: "Carrito",
  CHECKOUT: "Checkout",
  CART: "Cart",
  ORDERS: "Orders",
  TIENDA: "Tienda",
  ORDER_DETAIL: "OrderDetail",
  MIS_ORDENES: "Mis órdenes",
  DIRECCIONES: "Direcciones",
  NEW_PLACE: "NewPlace",
  PLACE_LIST: "PlaceList",
  PLACE_DETAIL: "PlaceDetail",
  MAP: "Map",
  SETTINGS: "Configuración",
  LOGOUT: "Logout",
};
